### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/helm-chart-releaser#12]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.
---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Apoorvyash** [comment]
hi, @thisiskaransgit @leecalcote
I have deep experience in figma and UI building, of mobile as well as web applications, Can you please assign me this issue?

**Comment by Ghat0tkach** [comment]
There you go @Apoorvyash ! All the best

**Comment by abhijeetgauravm** [comment]
I want to work on it. Can u assign me? @Ghat0tkach

**Comment by Ghat0tkach** [comment]
@Apoorvyash what's the status?

**Comment by Apoorvyash** [comment]
Hi @Ghat0tkach I am working on the issue, I will be finishing up the work and make a PR soon

**Comment by Ghat0tkach** [comment]
@Apoorvyash  , If you're facing any blockers feel free to ask for help in slack channel

**Comment by abhijeetgauravm** [comment]
@Ghat0tkach can i work?

**Comment by Ghat0tkach** [comment]
@abhijeetgauravm yes sure, please go ahead.

**Comment by abhijeetgauravm** [comment]
@Ghat0tkach actually - 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

actually this links arent for layer5 repo n...its link of meshery.....i think it should be updated n?

**Comment by abhijeetgauravm** [comment]
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

I think this link should be added n?

**Comment by Ghat0tkach** [comment]
Yes @abhijeetgauravm
 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by abhijeetgauravm** [comment]
ok making PR soon!
